### PR TITLE
Updated Readme.md

### LINKED ISSUE #2: Update the readme for the website

### PR DESCRIPTION
**Pull request by Kuljeet-123**
Fixes issue: #2

### CODE REVIEW

**Comment by Kuljeet-123** [comment]
@yellowwoods12 Please review it and merge it.

**Comment by Kuljeet-123** [comment]
@yellowwoods12 @plxity  its been 3 days .....please review my PR and merge it.

**Comment by plxity** [comment]
@Kuljeet-123 We have other tasks lined up too. Being impatient about your PR not getting merged won't be of any use. I request you to respect the guidelines. We will review and merge it shortly till then continue contributing.

**Comment by plxity** [comment]
@Kuljeet-123 And we obviously can't merge this before code for the website are not added.

**Comment by Kuljeet-123** [comment]
okay sir @plxity and sorry for my impatience.

**Review by yellowwoods12 — CHANGES_REQUESTED** [review]
@Kuljeet-123 provide better installation instructions keeping in mind people who know nothing about React.

**Comment by Kuljeet-123** [comment]
@yellowwoods12 I have updated according to your guidance.Please review it.

**Review by yellowwoods12 — APPROVED** [review]

**Review by AdityaSrivast — APPROVED** [review]

**Comment by plxity** [comment]
@Kuljeet-123 Mention the link of site in the readme.

**Comment by Kuljeet-123** [comment]
@plxity Which link I need to add in the README...Can you please tell me.

**Comment by arpit9667** [comment]
@Kuljeet-123 This one: https://react-dark.netlify.com/

**Comment by Kuljeet-123** [comment]
@plxity @arpit9667 @yellowwoods12 @AdityaSrivast I have updated the file.Please review it and merge it.

**Review by plxity — APPROVED** [review]

**Pull request merged**
