### PR TITLE
added website source code with implementation of react-dark library

### LINKED ISSUE #1: Add the source code for the website.

### PR DESCRIPTION
**Pull request by BhuwanChandra**
@arpit9667 @yellowwoods12 please review the PR and suggest what else do I need to add in the website.

fixes: #1

### CODE REVIEW

**Comment by plxity** [comment]
@BhuwanChandra Please add a demo link to your implementation.

**Comment by BhuwanChandra** [comment]
@plxity demo link: https://react-dark.netlify.com/
please review the website and suggest what else do I need to add in the website.

**Review by arpit9667 — APPROVED** [review]

**Review by plxity — CHANGES_REQUESTED** [review]
Please remove the yarn.lock file and other unnecessary file.

**Comment by BhuwanChandra** [comment]
@plxity removed unnecessary files.
please also add difficulty labels on this.

**Review by yellowwoods12 — APPROVED** [review]
looks good.

**Review by plxity — APPROVED** [review]
LGTM :+1:

**Pull request merged**
